{% set name = "mmgsuite" %}
{% set version = "5.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url: https://github.com/MmgTools/mmg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4c396dd44aec69e0a171a04f857e28aad2e0bbfb733b48b6d81a2c6868e86840

build:
  number: 0
  skip: true  # [py<3 or win]
  ignore_run_exports_from:
    - {{ compiler('cxx') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - git
    - setuptools-scm
    - cmake
    - make  # [not win]
    - jom  # [win]  
    - libscotch
    - iscd-commons
    - iscd-linearelasticity
  run:
    - libscotch
    - iscd-commons
    - iscd-linearelasticity

test:
  commands:
    - mmgs_O3 --version || true  # [unix]
    - mmg2d_O3 --version || true  # [unix]
    - mmg3d_O3 --version || true  # [unix]
    - test -f $PREFIX/lib/libmmg.so  # [linux]
    - test -f $PREFIX/lib/libmmg.dylib  # [osx]    
    - test -f $PREFIX/include/mmg/libmmg.h
    - test -f $PREFIX/include/mmg/libmmgf.h

about:
  home: https://www.mmgtools.org/mmg-open-source-consortium
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'mmg - Surface and volume remeshers'
  description: |
    open source software for bidimensional and tridimensional surface and volume remeshing
  doc_url: https://www.mmgtools.org/mmg-remesher-try-mmg/mmg-remesher-tutorials
  dev_url: http://www.salome-platform.org/

extra:
  recipe-maintainers:
    - ldallolio
    - fbordeu
