{% set name = "mmgsuite" %}
{% set version = "5.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/MmgTools/mmg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4c396dd44aec69e0a171a04f857e28aad2e0bbfb733b48b6d81a2c6868e86840

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - git
    - setuptools-scm
    - cmake
    - ninja
    - libscotch              # [not win]
    - iscd-commons           # [not win]
    - iscd-linearelasticity  # [not win]
  run:
    - libscotch              # [not win]
    - iscd-commons           # [not win]
    - iscd-linearelasticity  # [not win]

test:
  commands:
    - mmgs_O3 --version || true  # [unix]
    - mmg2d_O3 --version || true  # [unix]
    - mmg3d_O3 --version || true  # [unix]
    - test -f $PREFIX/lib/libmmg.so  # [linux]
    - test -f $PREFIX/lib/libmmg.dylib  # [osx]
    - test -f $PREFIX/include/mmg/libmmg.h
    - test -f $PREFIX/include/mmg/libmmgf.h

about:
  home: https://www.mmgtools.org/mmg-open-source-consortium
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'mmg - Surface and volume remeshers'
  description: |
    open source software for bidimensional and tridimensional surface and volume remeshing
  doc_url: https://www.mmgtools.org/mmg-remesher-try-mmg/mmg-remesher-tutorials
  dev_url: https://github.com/MmgTools/mmg

extra:
  recipe-maintainers:
    - ldallolio
    - fbordeu
